# Exploratory Analysis – Raw Banking Transaction Data

Notebook ini bertujuan untuk memahami struktur, karakteristik, dan kualitas awal data transaksi perbankan
sebelum dilakukan proses data cleaning dan penyimpanan ke database.

# Import & Load Data

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/Bank_Transaction_Fraud_Detection.csv")

## 1. Preview Data
Melihat beberapa baris awal untuk memahami bentuk umum data.

In [2]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
0,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,Osha Tella,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,4fa3208f-9e23-42dc-b330-844829d0c12c,23-01-2025,...,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0,INR,+9198579XXXXXX,Bitcoin transaction,oshaXXXXX@XXXXX.com
1,7c14ad51-781a-4db9-b7bd-67439c175262,Hredhaan Khosla,Female,51,Maharashtra,Nashik,Nashik Branch,Business,c9de0c06-2c4c-40a9-97ed-3c7b8f97c79c,11-01-2025,...,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0,INR,+9191074XXXXXX,Grocery delivery,hredhaanXXXX@XXXXXX.com
2,3a73a0e5-d4da-45aa-85f3-528413900a35,Ekani Nazareth,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,e41c55f9-c016-4ff3-872b-cae72467c75c,25-01-2025,...,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0,INR,+9197745XXXXXX,Mutual fund investment,ekaniXXX@XXXXXX.com
3,7902f4ef-9050-4a79-857d-9c2ea3181940,Yamini Ramachandran,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,7f7ee11b-ff2c-45a3-802a-49bc47c02ecb,19-01-2025,...,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0,INR,+9195889XXXXXX,Food delivery,yaminiXXXXX@XXXXXXX.com
4,3a4bba70-d9a9-4c5f-8b92-1735fd8c19e9,Kritika Rege,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,f8e6ac6f-81a1-4985-bf12-f60967d852ef,30-01-2025,...,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0,INR,+9195316XXXXXX,Debt repayment,kritikaXXXX@XXXXXX.com

## 2. Ukuran Dataset

In [3]:
print(f"Jumlah baris: {df.shape[0]}")
print(f"Jumlah kolom: {df.shape[1]}")

Jumlah baris: 200000
Jumlah kolom: 24

## 3. Struktur dan Tipe Data
Melihat tipe data setiap kolom serta indikasi missing values.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Customer_ID              200000 non-null  object
 1   Customer_Name            200000 non-null  object
 2   Gender                   200000 non-null  object
 3   Age                      200000 non-null  int64
 4   State                    200000 non-null  object
 5   City                     200000 non-null  object
 6   Bank_Branch              200000 non-null  object
 7   Account_Type             200000 non-null  object
 8   Transaction_ID           200000 non-null  object
 9   Transaction_Date         200000 non-null  object
 10  Transaction_Time         200000 non-null  object
 11  Transaction_Amount       200000 non-null  float64
 12  Merchant_ID              200000 non-null  object
 13  Transaction_Type         200000 non-null  object
 14  Merchant_Category        200000 non-null  object
 15  Account_Balance          200000 non-null  float64
 16  Transaction_Device       200000 non-null  object
 17  Transaction_Location     200000 non-null  object
 18  Device_Type              200000 non-null  object
 19  Is_Fraud                 200000 non-null  int64
 20  Transaction_Currency     200000 non-null  object
 21  Customer_Contact         200000 non-null  object
 22  Transaction_Description  200000 non-null  object
 23  Customer_Email           200000 non-null  object
dtypes: float64(2), int64(2), object(20)
memory usage: 36.6+ MB

## 4. Statistik Deskriptif

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer_ID,200000,200000,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Name,200000,142699,Aahana Kala,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,200000,2,Male,100452,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,200000.0,NaN,NaN,NaN,44.01511,15.288774,18.0,31.0,44.0,57.0,70.0
State,200000,34,Nagaland,6031,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,200000,145,Chandigarh,8135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bank_Branch,200000,145,Chandigarh Branch,8135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Account_Type,200000,3,Checking,66924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transaction_ID,200000,200000,4fa3208f-9e23-42dc-b330-844829d0c12c,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transaction_Date,200000,31,29-01-2025,6854,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transaction_Time,200000,77856,07:30:31,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transaction_Amount,200000.0,NaN,NaN,NaN,49538.015554,28551.874004,10.29,24851.345,49502.44,74314.625,98999.98
Merchant_ID,200000,200000,214e03c5-5c34-40d1-a66c-f440aa2bbd02,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transaction_Type,200000,5,Credit,40180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Merchant_Category,200000,6,Restaurant,33525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Account_Balance,200000.0,NaN,NaN,NaN,52437.988784,27399.507128,5000.82,28742.395,52372.555,76147.67,99999.95
Transaction_Device,200000,20,Self-service Banking Machine,21707,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transaction_Location,200000,148,"Kavaratti, Lakshadweep",5954,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Device_Type,200000,4,POS,50111,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Is_Fraud,200000.0,NaN,NaN,NaN,0.05044,0.218852,0.0,0.0,0.0,0.0,1.0
Transaction_Currency,200000,1,INR,200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Contact,200000,9000,+9191471XXXXXX,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transaction_Description,200000,172,Sports ticket,1268,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Email,200000,4779,krishnaXXX@XXXXX.com,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 5. Pemeriksaan Awal Kualitas Data

In [6]:
df.isnull().sum().sort_values(ascending=False)

Customer_ID                0
Customer_Name              0
Transaction_Description    0
Customer_Contact           0
Transaction_Currency       0
Is_Fraud                   0
Device_Type                0
Transaction_Location       0
Transaction_Device         0
Account_Balance            0
Merchant_Category          0
Transaction_Type           0
Merchant_ID                0
Transaction_Amount         0
Transaction_Time           0
Transaction_Date           0
Transaction_ID             0
Account_Type               0
Bank_Branch                0
City                       0
State                      0
Age                        0
Gender                     0
Customer_Email             0
dtype: int64

In [7]:
duplicate_count = df.duplicated().sum()
duplicate_count

0

In [8]:
df[df.duplicated()]

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Gender, Age, State, City, Bank_Branch, Account_Type, Transaction_ID, Transaction_Date, Transaction_Time, Transaction_Amount, Merchant_ID, Transaction_Type, Merchant_Category, Account_Balance, Transaction_Device, Transaction_Location, Device_Type, Is_Fraud, Transaction_Currency, Customer_Contact, Transaction_Description, Customer_Email]
Index: []

[0 rows x 24 columns]

## 6. Ringkasan Temuan Awal

Dataset transaksi perbankan ini terdiri dari **200.000 baris dan 24 kolom**, yang merepresentasikan aktivitas transaksi nasabah pada berbagai cabang bank di India.

**Struktur data:**
- Terdapat **identifier unik** untuk entitas utama:
  - `Customer_ID` (unik per baris)
  - `Transaction_ID` (unik per transaksi)
  - `Merchant_ID` (unik per merchant)
- Data mencakup kombinasi informasi:
  - **Nasabah**: `Customer_Name`, `Gender`, `Age`, `State`, `City`
  - **Akun & cabang**: `Account_Type`, `Bank_Branch`
  - **Transaksi**: `Transaction_Date`, `Transaction_Time`, `Transaction_Amount`, `Transaction_Type`
  - **Merchant**: `Merchant_Category`
  - **Konteks transaksi**: `Transaction_Device`, `Device_Type`, `Transaction_Location`
  - **Indikasi risiko**: `Is_Fraud`

**Tipe data dan format:**
- Kolom numerik utama:
  - `Transaction_Amount` (rata-rata ±49.5K, rentang 10–98K)
  - `Account_Balance` (rata-rata ±52.4K)
  - `Age` (rentang 18–70)
- Kolom target `Is_Fraud` bersifat biner (0/1) dengan proporsi fraud sekitar **5%**, menunjukkan **class imbalance** yang perlu diperhatikan pada analisis lanjutan.
- Kolom tanggal (`Transaction_Date`) dan waktu (`Transaction_Time`) masih berbentuk **string**, sehingga perlu parsing ke tipe datetime pada tahap technical cleaning.

**Kualitas data mentah:**
- Tidak ditemukan **missing values** pada seluruh kolom.
- Tidak terdapat duplikasi baris secara eksplisit.
- Beberapa kolom bersifat **high-cardinality**, seperti `Customer_Name`, `Customer_Email`, dan `Customer_Contact`, yang perlu dipertimbangkan penggunaannya pada tahap analisis dan visualisasi.
- Kolom `Transaction_Currency` hanya memiliki satu nilai unik (`INR`), sehingga secara analitis tidak memberikan variasi.

**Kesimpulan awal:**
Dataset ini **lengkap secara teknis** dan siap untuk masuk ke tahap **technical data cleaning menggunakan Python**, khususnya untuk:
- standarisasi nama kolom,
- konversi tipe data tanggal & waktu,
- penyiapan skema yang konsisten sebelum dimuat ke PostgreSQL sebagai raw table.